using Npgsql;

namespace FrostFarmer;

public sealed class PostgresDatabase(NpgsqlDataSource source) : IFrostDatabase
{
    public async Task InitializeAsync(CancellationToken ct=default){await using var c=source.CreateCommand(Schema);await c.ExecuteNonQueryAsync(ct);}
    public async Task<IReadOnlyList<WorkTask>> TasksAsync(){var list=new List<WorkTask>();await using var c=source.CreateCommand("SELECT id,goal,status,priority,created_at,updated_at,result,error FROM tasks ORDER BY created_at DESC");await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(ReadTask(r));return list;}
    public async Task<WorkTask?> TaskAsync(Guid id){await using var c=source.CreateCommand("SELECT id,goal,status,priority,created_at,updated_at,result,error FROM tasks WHERE id=$1");c.Parameters.AddWithValue(id);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?ReadTask(r):null;}
    public async Task SaveTaskAsync(WorkTask t){await using var c=source.CreateCommand("INSERT INTO tasks VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET goal=$2,status=$3,priority=$4,updated_at=$6,result=$7,error=$8");c.Parameters.AddWithValue(t.Id);c.Parameters.AddWithValue(t.Goal);c.Parameters.AddWithValue((int)t.Status);c.Parameters.AddWithValue(t.Priority);c.Parameters.AddWithValue(t.CreatedAt);c.Parameters.AddWithValue((object?)t.UpdatedAt??DBNull.Value);c.Parameters.AddWithValue((object?)t.Result??DBNull.Value);c.Parameters.AddWithValue((object?)t.Error??DBNull.Value);await c.ExecuteNonQueryAsync();}
    public async Task AddMemoryAsync(MemoryEntry e){await using var c=source.CreateCommand("INSERT INTO memory VALUES($1,$2,$3,$4)");c.Parameters.AddWithValue(e.Id);c.Parameters.AddWithValue(e.Scope);c.Parameters.AddWithValue(e.Content);c.Parameters.AddWithValue(e.CreatedAt);await c.ExecuteNonQueryAsync();}
    public async Task<IReadOnlyList<MemoryEntry>> SearchMemoryAsync(string q,int limit=20){var list=new List<MemoryEntry>();await using var c=source.CreateCommand("SELECT id,scope,content,created_at FROM memory WHERE content ILIKE $1 OR scope ILIKE $1 ORDER BY created_at DESC LIMIT $2");c.Parameters.AddWithValue("%"+q+"%");c.Parameters.AddWithValue(limit);await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetFieldValue<DateTimeOffset>(3)));return list;}
    public async Task<int> UserCountAsync(){await using var c=source.CreateCommand("SELECT count(*) FROM users");return Convert.ToInt32(await c.ExecuteScalarAsync());}
    public async Task<UserAccount?> UserByNameAsync(string n)=>await FindUser("username",n);
    public async Task<UserAccount?> UserByIdAsync(Guid id)=>await FindUser("id",id);
    private async Task<UserAccount?> FindUser(string column,object value){await using var c=source.CreateCommand($"SELECT id,username,password_hash,role,created_at,enabled FROM users WHERE {column}=$1");c.Parameters.AddWithValue(value);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.GetBoolean(5)):null;}
    public async Task SaveUserAsync(UserAccount u){await using var c=source.CreateCommand("INSERT INTO users VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET username=$2,password_hash=$3,role=$4,enabled=$6");c.Parameters.AddWithValue(u.Id);c.Parameters.AddWithValue(u.Username);c.Parameters.AddWithValue(u.PasswordHash);c.Parameters.AddWithValue(u.Role);c.Parameters.AddWithValue(u.CreatedAt);c.Parameters.AddWithValue(u.Enabled);await c.ExecuteNonQueryAsync();}
    public async Task<bool> TryCreateFirstUserAsync(UserAccount u){await using var connection=await source.OpenConnectionAsync();await using var tx=await connection.BeginTransactionAsync();await using(var lockCommand=new NpgsqlCommand("SELECT pg_advisory_xact_lock(407040)",connection,tx))await lockCommand.ExecuteNonQueryAsync();await using(var count=new NpgsqlCommand("SELECT count(*) FROM users",connection,tx))if(Convert.ToInt32(await count.ExecuteScalarAsync())!=0){await tx.RollbackAsync();return false;}await using(var insert=new NpgsqlCommand("INSERT INTO users VALUES($1,$2,$3,$4,$5,$6)",connection,tx)){insert.Parameters.AddWithValue(u.Id);insert.Parameters.AddWithValue(u.Username);insert.Parameters.AddWithValue(u.PasswordHash);insert.Parameters.AddWithValue(u.Role);insert.Parameters.AddWithValue(u.CreatedAt);insert.Parameters.AddWithValue(u.Enabled);await insert.ExecuteNonQueryAsync();}await tx.CommitAsync();return true;}
    public async Task SaveTokenAsync(AccessToken t){await using var c=source.CreateCommand("INSERT INTO access_tokens VALUES($1,$2,$3,$4,$5); DELETE FROM access_tokens WHERE expires_at < now()");c.Parameters.AddWithValue(t.Id);c.Parameters.AddWithValue(t.UserId);c.Parameters.AddWithValue(t.TokenHash);c.Parameters.AddWithValue(t.ExpiresAt);c.Parameters.AddWithValue(t.CreatedAt);await c.ExecuteNonQueryAsync();}
    public async Task<AccessToken?> TokenByHashAsync(string h){await using var c=source.CreateCommand("SELECT id,user_id,token_hash,expires_at,created_at FROM access_tokens WHERE token_hash=$1 AND expires_at>now()");c.Parameters.AddWithValue(h);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetFieldValue<DateTimeOffset>(3),r.GetFieldValue<DateTimeOffset>(4)):null;}
    public async Task RevokeTokenAsync(string h){await using var c=source.CreateCommand("DELETE FROM access_tokens WHERE token_hash=$1");c.Parameters.AddWithValue(h);await c.ExecuteNonQueryAsync();}
    public async Task<bool> IsHealthyAsync(CancellationToken ct=default){try{await using var c=source.CreateCommand("SELECT 1");return Convert.ToInt32(await c.ExecuteScalarAsync(ct))==1;}catch{return false;}}
    private static WorkTask ReadTask(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetString(1),(WorkStatus)r.GetInt32(2),r.GetInt32(3),r.GetFieldValue<DateTimeOffset>(4),r.IsDBNull(5)?null:r.GetFieldValue<DateTimeOffset>(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7));
    private const string Schema="""
CREATE TABLE IF NOT EXISTS tasks(id uuid PRIMARY KEY,goal text NOT NULL,status int NOT NULL,priority int NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz,result text,error text);
CREATE TABLE IF NOT EXISTS memory(id uuid PRIMARY KEY,scope text NOT NULL,content text NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,username text UNIQUE NOT NULL,password_hash text NOT NULL,role text NOT NULL,created_at timestamptz NOT NULL,enabled boolean NOT NULL);
CREATE TABLE IF NOT EXISTS access_tokens(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_tasks_status_priority ON tasks(status,priority DESC,created_at);
CREATE INDEX IF NOT EXISTS ix_memory_created ON memory(created_at DESC);
""";
}
